events {}

http {
  upstream user_service { server user-service:3000; }
  upstream wss_service { server wss-service:8081; }

  server {
    listen 80;

    location /ws {
      proxy_pass http://wss_service;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    location /rooms {
      proxy_pass http://wss_service;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
    }

    location /users {
      proxy_pass http://user_service;
      proxy_set_header Host $host;
      proxy_set_header Authorization $http_authorization;
    }
  }
}
