name: Build Client
description: Installs dependencies and build the static react app 

# composite reusable action
runs:
    using: composite
    steps:
      - uses: actions/setup-node@v4
        with: 
          node-version: 24.22
      - run: npm ci 
        shell: bash 
      - run: npm run build 
        shell: bash 
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/