name: Reusable Test Phase
on: 
  workflow_call:
    inputs:
        run_frontend:
          required: true
          type: boolean
        run_backend:
          required: true
          type: boolean

jobs:
  test-frontend:
    if: ${{inputs.run_frontend}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.22
      - run: npm ci
      - run: npm test

  test-backend:
    if: ${{inputs.run_backend}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # setup-go@v5 automatically monitors  go.sum file for caching out-of-the-box.
      - uses: actions/setup-go@v5
        with:
          go-version: 1.26
      - run: go mod download
      # Test with folder structure specify
      - run: go test -v ./...